version: '3'
services:
  db:
    image: mongo
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
